name: PoemOfTheDay
options:
  deploymentTarget:
    iOS: "17.0"
settings:
  SWIFT_VERSION: 5.0
  IPHONEOS_DEPLOYMENT_TARGET: 17.0
  CURRENT_PROJECT_VERSION: 1
  MARKETING_VERSION: 1.0
  ARCHS: arm64
  ENABLE_BITCODE: NO
  VALIDATE_PRODUCT: NO
  DEAD_CODE_STRIPPING: YES
configs:
  Debug: debug
  Release: release
targets:
  PoemOfTheDay:
    type: application
    platform: iOS
    sources:
      - ios/App
      - ios/Shared
    resources:
      - poem.json
    dependencies:
      - target: PoemWidgetExtension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aksha.poemoftheday
        INFOPLIST_FILE: ios/App/Info.plist
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: ""
        DEVELOPMENT_TEAM: ""
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: NO
        GENERATE_INFOPLIST_FILE: NO
  PoemWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - ios/Widget
      - ios/Shared
    resources:
      - poem.json
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aksha.poemoftheday.widget
        INFOPLIST_FILE: ios/Widget/Info.plist
        TARGETED_DEVICE_FAMILY: "1,2"
        SKIP_INSTALL: YES
        APPLICATION_EXTENSION_API_ONLY: YES
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: ""
        DEVELOPMENT_TEAM: ""
        GENERATE_INFOPLIST_FILE: NO
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
