name: PoemOfTheDay
options:
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
settings:
  base:
    SWIFT_VERSION: "5"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    CURRENT_PROJECT_VERSION: "1"
    MARKETING_VERSION: "1.0"
    ARCHS: arm64
    ENABLE_BITCODE: "NO"
    VALIDATE_PRODUCT: "NO"
    CODE_SIGNING_ALLOWED: "NO"
    CODE_SIGNING_REQUIRED: "NO"
    CODE_SIGN_IDENTITY: ""
configs:
  Debug: debug
  Release: release
schemes:
  PoemOfTheDay:
    build:
      targets:
        PoemOfTheDay: all
        PoemWidgetExtension: all
    run:
      config: Debug
    archive:
      config: Release
targets:
  PoemOfTheDay:
    type: application
    platform: iOS
    sources:
      - path: ios/App
      - path: ios/Shared
    resources:
      - path: poem.json
    dependencies:
      - target: PoemWidgetExtension
        embed: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aksha.poemoftheday
        INFOPLIST_FILE: ios/App/Info.plist
        GENERATE_INFOPLIST_FILE: "NO"
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: "NO"
  PoemWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: ios/Widget
      - path: ios/Shared
    resources:
      - path: poem.json
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aksha.poemoftheday.widget
        INFOPLIST_FILE: ios/Widget/Info.plist
        GENERATE_INFOPLIST_FILE: "NO"
        TARGETED_DEVICE_FAMILY: "1,2"
        SKIP_INSTALL: "YES"
        APPLICATION_EXTENSION_API_ONLY: "YES"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
