name: PoemOfTheDay
options:
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    SWIFT_VERSION: "5"
    CURRENT_PROJECT_VERSION: "1"
    MARKETING_VERSION: "1.0"
configs:
  Debug: debug
  Release: release
schemes:
  PoemOfTheDay:
    build:
      targets:
        PoemOfTheDay: all
        PoemWidgetExtension: all
    run:
      config: Debug
    archive:
      config: Release
targets:
  PoemOfTheDay:
    type: application
    platform: iOS
    sources:
      - path: ios/App
      - path: ios/Shared
    resources:
      - path: poem.json
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aksha.poemoftheday
        INFOPLIST_FILE: ios/App/Info.plist
        GENERATE_INFOPLIST_FILE: "NO"
        TARGETED_DEVICE_FAMILY: "1,2"
    entitlements:
      path: ios/App/PoemOfTheDay.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.aksha.poemoftheday
    dependencies:
      - target: PoemWidgetExtension

  PoemWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: ios/Widget
      - path: ios/Shared
    resources:
      - path: poem.json
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aksha.poemoftheday.widget
        INFOPLIST_FILE: ios/Widget/Info.plist
        GENERATE_INFOPLIST_FILE: "NO"
        TARGETED_DEVICE_FAMILY: "1,2"
    entitlements:
      path: ios/Widget/PoemWidgetExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.aksha.poemoftheday
